### ISSUE TITLE
Firefox - NSS_3.113 not found

### ISSUE THREAD

**Issue by rohrbachger** [Thinstation/thinstation-ng#73]
I have some issues with certificates for omnissa and also on firefox.
It seems, that nss is not in the right version or not installed.

On the ng-version it works different , where do I find he ports?

**Comment by Doncuppjr** [comment]
We use Fedora RPM's for NG

**Comment by rohrbachger** [comment]
Do I understand right, in the chroot I have to run dnf install nss?

For my understanding: In the packages folder ( like firefox )  I have to check, if the dependency 
packages like nss are already installed with dnf? 
I'ḿ one of the Omnissa /View Horizon users, and I want now to get it running on he NG.
I do see a lots of benefits, but the first steps take some time.
It`s good that some other guys with probably more knowledge deal with this.
As we are using Teams with 6.2 successfully we have some time to get it running on NG.

**Comment by Doncuppjr** [comment]
Use the horizon package instead of vmview. Should be working already.

**Comment by rohrbachger** [comment]
This I had tested.
There are some dependencies missing, like nss, nss-softokn, ca-certificates and probably also p11-kit.
If there is no browser installed, this packages are missing. We are connecting to external servers, we check certificates.
I have still a problem with pcoip protocol, the windows bar is not showing on the bottom.
Blast works fine, but in general we prefere pcoip.
So I will continue testing, but it looks not too bad..
Image is now less then 400MB, I deleted some files for html access in horizon, that are not needed for blast and pcoip.

**Comment by Doncuppjr** [comment]
Okay, I added the dependencies to horizon package.
